# -*- MakeFile -*-

# MACRO = substitute with this

# directories

ESTDIS_DIR = ../../../

MODULES_DIR = $(ESTDIS_DIR)/modules/
ABOUT_DIR = $(MODULES_DIR)/about/
TST_DIR = $(ABOUT_DIR)/tst/
OBJ_DIR = $(TST_DIR)/obj/

# target: dependencies
#	action

all:
	cd $(OBJ_DIR) && $(MAKE) && cd ..

clean:
	cd $(OBJ_DIR) && $(MAKE) clean && cd ..
