# -*- MakeFile -*-

# MACRO = substitute with this

# directories

ESTDIS_DIR = ../../

MODULES_DIR = $(ESTDIS_DIR)/modules/
CTRL_DIR = $(MODULES_DIR)/ctrl/
OBJ_DIR = $(CTRL_DIR)/obj/
TST_DIR = $(CTRL_DIR)/tst/

# target: dependencies
#	action

all:
	cd $(OBJ_DIR) && $(MAKE) && cd ..

clean:
	cd $(OBJ_DIR) && $(MAKE) clean && cd ..
